/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Phase_Only_Correlation;

import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Test;

class LibraryTest
{
    @Test
    void someLibraryMethodReturnsTrue()
    {
        Phase_Only_Correlation classUnderTest = new Phase_Only_Correlation();
        //assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
