/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Phase_Only_Correlation;

public class Phase_Only_Correlation {
    public boolean someLibraryMethod() {
        return true;
    }
}
